# Generated by Django 4.2 on 2024-10-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_caterogy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caterogy',
            new_name='category',
        ),
    ]
