# Generated by Django 4.2 on 2024-10-26 15:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_caterogy_product_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
